apiVersion: v1
kind: Namespace
metadata:
  name: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
  namespace: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - image: quay.io/skupper/salty-pug-console
        name: salty-pug-console
        env:
        - name: STORE_SERVICE_HOST_ANY
          value: store-any.svc
        - name: STORE_SERVICE_HOST_ALL
          value: store-all.svc
        - name: FACTORY_SERVICE_HOST_ANY
          value: factory-any.svc
        - name: FACTORY_SERVICE_HOST_ALL
          value: factory-all.svc
