apiVersion: v1
kind: Namespace
metadata:
  name: console
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: console
  name: console
  namespace: console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: console
  template:
    metadata:
      labels:
        app: console
    spec:
      containers:
      - image: quay.io/skupper/salty-pug-console
        name: salty-pug-console
        env:
        - name: STORE_SERVICE_HOST
          value: store.store-1.svc
        - name: STORE_SERVICE_PORT
          value: "8080"
        - name: FACTORY_SERVICE_HOST
          value: factory.factory-1.svc
        - name: FACTORY_SERVICE_PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: console
  name: console
  namespace: console
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: console
  type: LoadBalancer
